<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<module category="" descriptorversion="1.0" entrypoint="testjavaproject/Start" forcesubdialogcall="false" frameworkversion="08.12.11.01" iconlarge="icons/defaultapplicationlg.gif" iconsmall="icons/defaultapplicationsm.gif" modifyInputs="false" modifyOutputs="false" nature="com.avaya.sce.core.speechnature" outputmultipart="false" paramasnamelist="false" provider="" submitmethod="get" version="1.0.0" webname="testjavaproject">
    <description/>
    <language name="spanish" root="es-la"/>
    <dependencies/>
</module>
